development:
  bucket: spectrum-bucket-pro
  access_key_id: <%= ENV['S3_ID'] %>
  secret_access_key: <%= ENV['S3_KEY'] %>
test:
  bucket: spectrum-bucket-test
  access_key_id: <%= ENV['S3_ID'] %>
  secret_access_key: <%= ENV['S3_KEY'] %>
production:
  bucket: spectrum-bucket-pro
  access_key_id: <%= ENV['S3_ID'] %>
  secret_access_key: <%= ENV['S3_KEY'] %>